# Generated by Django 4.1.6 on 2023-02-11 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='mail',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
    ]
