# Generated by Django 4.1.6 on 2023-02-12 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0002_remove_user_mail_remove_user_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
